{% set name = "MPAS-Analysis" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/MPAS-Dev/{{ name }}/archive/{{ version }}.tar.gz
  sha256: a92fe368ff0031e5608479935a7dfa1a8b8f238c66402877de91b7c9d8b0f069

build:
    number: 1
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"
    noarch: python
    entry_points:
        - mpas_analysis = mpas_analysis.__main__:main
        - download_analysis_data = mpas_analysis.__main__:download_analysis_data

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - matplotlib <=2.2.3|>=3.0.2
    - netcdf4
    - xarray >=0.10.0
    - dask
    - bottleneck
    - basemap
    - lxml
    - nco >=4.7.9
    - pillow
    - cmocean
    - progressbar2
    - requests
    - pyproj
    - setuptools
    - shapely

test:
  requires:
    - pytest
  imports:
    - mpas_analysis
    - pytest
  commands:
    - pytest --pyargs mpas_analysis

about:
  home: https://github.com/MPAS-Dev/MPAS-Analysis
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Analysis of MPAS-Ocean and MPAS-Seaice simulations results'
  description: |
    Analysis for simulations produced with Model for Prediction Across Scales
    (MPAS) components and the Energy Exascale Earth System Model (E3SM), which
    used those components.
  doc_url: http://mpas-analysis.readthedocs.io
  dev_url: https://github.com/MPAS-Dev/MPAS-Analysis

extra:
  recipe-maintainers:
    - xylar
    - jhkennedy
