{% set name = "MPAS-Analysis" %}
{% set version = "1.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/MPAS-Dev/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 9fce7561efa0d512567f89219a1f1642210810523a550b1974a17fdba1b6f544

build:
    number: 1
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"
    noarch: python
    entry_points:
        - mpas_analysis = mpas_analysis.__main__:main
        - download_analysis_data = mpas_analysis.download_data:download_analysis_data
        - download_natural_earth_110m = mpas_analysis.download_data:download_natural_earth_110m

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - matplotlib <3.0.0|>=3.0.2
    - netcdf4
    - xarray >=0.10.0,<0.14.1
    - dask
    - bottleneck
    - basemap
    - lxml
    - nco >=4.8.1
    - pillow
    - cmocean
    - progressbar2
    - requests
    - pyproj
    - setuptools
    - shapely
    - cartopy
    - geometric_features
    - gsw
    - pyremap

test:
  requires:
    - pytest
  imports:
    - mpas_analysis
    - pytest
  commands:
    - pytest --pyargs mpas_analysis
    - mpas_analysis --help
    - download_analysis_data --help
    - download_natural_earth_110m --help

about:
  home: https://github.com/MPAS-Dev/MPAS-Analysis
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Analysis of MPAS-Ocean and MPAS-Seaice simulations results'
  description: |
    Analysis for simulations produced with Model for Prediction Across Scales
    (MPAS) components and the Energy Exascale Earth System Model (E3SM), which
    used those components.
  doc_url: http://mpas-analysis.readthedocs.io
  dev_url: https://github.com/MPAS-Dev/MPAS-Analysis

extra:
  recipe-maintainers:
    - xylar
    - jhkennedy
