travis:
  secure:
    BINSTAR_TOKEN: Sz1NkOu8lykjpX0h4mJ+Di5hcqpNel/Ia5/oK/iKZVPwMWsRnl6pbKmuZdwbEUoc/ow48HHtRio1y0W/n0P7BseEN68SRMvfKUcLcApUFsdzMab0aw6NVtCLB5GZMn87krrOkFE3HoSK9w24iXmZDh8RiRitQkLD4ElyuYJIdqo0R2FxEowzbQKmrHspMR/nXGPhUXeLZQb8G4xuODPhXjmWL5mY980hAAOgRsTGWIJkCYirWEHfH62WA2/rgK3VycFLzlBDanMqnpdt9yhe5+pfQOZnxfgxR2bGEcDK3sVWdkw8QGwrbJRvSu633AxhOoakJ2a0daEsSq5/4V6qfptKU/AxIEj6T0tSzz/wvt40qkwre7A3G+zjfox+5dO6d4ZGGZ9AlsjqkN6OtAFYc3FvfaXOvoAbg2UhaEwzB1Fn2H6utEXsyPPQhDKNEAJLsM5o9ZCezkkdwA4iLv2R/UYk7ltugwCDCwAJLcbb+gnKfgnsL6QyuUJICsZMkg2FWKou6FKGVliDxGSYwSPOqY7AOkpi/sysFWvW989kj2KPZe7h9USyMELoLi66H6kurEsJB60DFyIt1GPf7QpmUIastLPEDyQ7iUelJITVEgVowVWEYmE0iZN0RzgNBzl0oSJEi9JGw+qUyuZ9diSMDthPLsl3RiA/Wjr0wJkazmA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
